project:
  type: website
  output-dir: docs

website:
  title: "Taylor Crockett"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - text: "Research"
        menu:
        - href: SpaceSilkRoad.qmd
          text: "Space Silk Road (2021)"
        - href: space_program_clustering.qmd
          text: "How I clustered space program data"
      - text: "Projects"
        menu:
        # - href: https://twcrockett.github.io/TXelection_4317
        #   text: "2022 Texas Gubernatorial Election (2022)—broken right now 😢" 
        - href: LunarPhases.qmd
          text: "Lunar Phases and Fatal Crashes"
      - text: "EPPS 6302 (Fall 2023)"
        menu: 
          - href: assignment_01.qmd
            text: "Assignment 1"
          - href: assignment_02.qmd
            text: "Assignment 2"   
          - href: assignment_03.qmd
            text: "Assignment 3"
          - href: assignment_05.qmd
            text: "Assignment 5"
          - href: assignment_06.qmd
            text: "Assignment 6"
          - href: assignment_07.qmd
            text: "Assignment 7"
          - href: assignment_08.qmd
            text: "Assignment 8"         
      - text: "Expanded classwork"
        menu:
        - href: EnvironmentalRacismGreenSpace.qmd
          text: "Environmental Racism and Green Space (2022)"
        - href: Assignment02.qmd
          text: "Taiwanese independence sentiments: bar chart" 
        - href: Assignment03.qmd
          text: "Taiwanese independence sentiments: boxplot and PCA"
      - href: CV.qmd
        text: "CV"
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "GitHub"
        href: https://github.com/twcrockett
      - text: "Contact me"
        href: contact.qmd
      - text: "Last updated 11 April 2023"
        href: https://github.com/twcrockett/twcrockett.github.io

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

